CREATE TABLE IF NOT EXISTS "GroupUsers" (
  "GroupId" uuid NOT NULL REFERENCES "Groups" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "UserId" uuid NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  UNIQUE ("GroupId", "UserId"),
  PRIMARY KEY ("GroupId", "UserId")
);