"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var views_1 = require("./views");
var express = require('express');
var app = express();
var port = 3000;
app.use(express.json());
app.get('/', views_1.homepage);
app.delete('/user/:id', views_1.deleteUser);
app.get('/user/:id', views_1.getUser);
app.put('/user/:id', views_1.updateUser);
app.get('/user', views_1.getAutoSuggestUsers);
app.post('/user', views_1.addUser);
app.listen(port, function () { return console.log("Server started on port " + port); });
